### ISSUE TITLE
Auto linking (w/ anchor) syntax issue

### ISSUE THREAD

**Issue by raybit** [naokazuterada/MarkdownTOC#23] opened 2014-08-02 17:08 UTC
Hi, 
  I see and tried the auto-link-fill feature where we can add an "[with-anchor]" with one header.
  But obviously, this "[with-anchor]"  style will be consider as the mark of an inline link of that header line and will be shown in the export file whereas the TOC part just extract it as id but not use its context. So, it go against the markdown's syntax. And this cause the cool feature become useless.

Thanks
ray

**Comment by MrLeeh** [comment] 2015-06-01 05:20
@johnathanz got the same propblem.

If I use the *square* brackets for links there will be no Links when viewing it with MarkdownPreview. With the *round* brackets it works but only for *Markdown* style, not *Github*. 

Also Links with non-ascii characters such as (Ü, Ä, Ö, ... ) don' t work.

**Comment by jonasbn** [comment] 2017-04-09 22:39
is the last problem described duplicate of the issues: #79 and #56 ?

**Comment by naokazuterada** [comment] 2017-08-02 01:25
This may be fixed in [2.4.0](https://github.com/naokazuterada/MarkdownTOC/releases/tag/2.4.0).

**Closed by naokazuterada** 2017-08-02 01:25 UTC
Labels: bug
