### ISSUE TITLE
Use html to make the tag `<!-- MarkdownTOC -->` hidden when rendering

### ISSUE THREAD

**Issue by YingmingHu** [naokazuterada/MarkdownTOC#67] opened 2016-06-01 03:30 UTC
Use code:   
- `<p style="hidden"> <!-- MarkdownTOC --> </p>`
- `<p style="hidden"><!-- /MarkdownTOC --> </p>`

Will present (nothing):  
<p style="hidden">  </p>
<p style="hidden"> </p>

**Comment by naokazuterada** [comment] 2016-06-01 05:10
Plugin might search TOC tags with regex `^<!-- MarkdownTOC .*-->\n` and `^<!-- /MarkdownTOC -->\n`
You cannot add anything before and after these tags.

https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py#L52
https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py#L108

**Comment by naokazuterada** [comment] 2016-06-01 05:14
TOC tags might be hidden in HTML.Why did you add `p`?

**Comment by YingmingHu** [comment] 2016-06-01 05:46
I knew that tags are comments in HTML, but it still can be shown in gitlab's markdown renderer, i think it's just a feature gap between different markdown syntax.
So, please close this issue if there is not a elegant solution.

**Comment by YingmingHu** [comment] 2016-06-01 05:57
PS: this workaround solution still cannot work on gitlab, just works on [OmniMarkupPreviewer](https://github.com/timonwong/OmniMarkupPreviewer), a markdown previewer extension on Sublime Text.

**Comment by naokazuterada** [comment] 2016-06-01 06:11
Ummm... I checked it on gitlabCE(v8.1.2), gitlab.com, and OmniMarkupPreviewer, but there is no problem.
Please give me more information to reproduce if you can.

**Comment by YingmingHu** [comment] 2016-06-08 02:49
Gitlab what I used is `GitLab 7.6.2`,  it shows like below picture:
![image](https://cloud.githubusercontent.com/assets/1429198/15881192/909c2708-2d66-11e6-9df7-03fd3e5543da.png)
And OmniMarkupPreviewer works well, comments will not be shown.

**Comment by naokazuterada** [comment] 2016-06-08 03:30
Thank you for reply and screen capture!

It seems to be Gitlab's bug (or spec?).
Unfortunately I cannot give you a solution, so I close this issue. Sorry... 😢 

**Just Idea**
Maybe the problem is that Gitlab shows comments in HTML.
So if you replace TOC tags in [source code](https://github.com/naokazuterada/MarkdownTOC/blob/master/MarkdownTOC.py) to HTML tag format (e.g. `<div MarkdownTOC autoanchor="0">...</div>`), Gitlab will not show it.

**Closed by naokazuterada** 2016-06-08 03:30 UTC

**Comment by YingmingHu** [comment] 2016-06-08 09:31
Thanks for your quick reply and providing solution.
It seems not this extension's issue, neither can be fixed elegantly.
