### ISSUE TITLE
'cannot find TOC tags' err when insert new TOC

### ISSUE THREAD

**Issue by Nick-Alam** [naokazuterada/MarkdownTOC#58] opened 2016-02-22 03:44 UTC
Hi team,

After I installed MarkdownTOC on `sublimetext 3`  and then tried to `inert new TOC`, I got this err:

`'cannot find TOC tags'`

``` html
Traceback (most recent call last):
  File "Y:\Dev\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "MarkdownTOC in Y:\Dev\Sublime Text 3\Data\Installed Packages\MarkdownTOC.sublime-package", line 40, in run
TypeError: Can't convert 'bool' object to str implicitly
```

But I have successfully installed MarkdownTOC on my another PC and it works fine.

Could you pls help with this?

**Comment by jonasbn** [comment] 2017-04-09 22:13
Hi Nick-Alam,

Could you please provide information on operating system and possibly exact version/build of Sublime Text.

Did you install via Package Control or some other way.

jonasbn

**Comment by naokazuterada** [comment] 2017-09-26 11:28
Hi @Nick-Alam 

I'm so sorry for late reply, but I haven't represent this issue yet.
Please let me know if you still have this problem, and give me more information (how to reproduce / example / etc.).

I'm planning to close this issue in the next week if I won't get any progress.

**Comment by naokazuterada** [comment] 2017-10-08 06:29
Close this because of 'no information for reproduce'.

**Closed** 2017-10-08 06:28 UTC
Labels: bug
